### ISSUE TITLE
Installation not possible with ftp links

### ISSUE THREAD

**Issue by arkays-code** [3dem/model-angelo#9] opened 2022-10-07 00:15 UTC
Hi,

I work for a corporate Pharma that wishes to evaluate model-angelo.
In attempting to install the package I've found that the code tries to download files via ftp.

Specifically the code is here:

torch_utils.py:        f"ftp://ftp.mrc-lmb.cam.ac.uk/pub/scheres/modelangelo/{bundle_name}.zip"

ftp has been considered outmoded by the world for some time.  To the extent that even chrome no longer supports retrieval of files from any ftp sites.

Our corporation (and I expect most all), have banned all internal and external use of ftp sites due to the insecure nature of the protocol.

I am therefore writing this only to request that you please consider moving (or asking the powers that be), to provide more modern and secure methods of file transfer. sftp, https etc.

Having to disassemble and manually install the application (downloading these files on a private open connection), due to a lack of being able to source the materials commercially is quite frustrating.

While I thank you for making your code available to the public and understand that you have no obligation whatsoever to change, I just wanted to mention this as I run across this problem often and I always ask the maintainers of such repositories to consider seeking better alternatives.

Thanks for your time.

Cheers,

Rick.

**Comment by jamaliki** [comment] 2022-10-07 11:02
Hi,

Thank you for your interest. Sorry, I was not aware that this is a problem. We are currently in the process of migrating it to a more secure protocol based on your feedback. In the meantime, is there some way we can help with transferring the weights in another manner?

Best,
Kiarash.

**Comment by biochem-fan** [comment] 2022-10-07 11:10
This is scientific software with a preprint, so [Zenodo](https://zenodo.org/) is an option. Note that once you upload a file, you cannot replace it. A newer model will be another entry. This might sound cumbersome but is actually a good thing from the reproducibility point of view.

**Comment by jamaliki** [comment] 2022-10-07 12:06
Yes, that looks like a good option

**Comment by jamaliki** [comment] 2022-10-07 13:55
Dear @arkays-code , 

As of 3139db26cf4a78474184b8024fbb28ee5ba01c09, we are now using HTTPS for downloading the model weights. I hope this is more convenient.

Best,
Kiarash.

**Closed** 2022-10-10 08:42 UTC
